// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH_xARFXl7KFwcgB6__ox1BLOQZuWvlzY',
    appId: '1:278722220216:web:81e5376278d74c59eba44d',
    messagingSenderId: '278722220216',
    projectId: 'buy-it-29668',
    authDomain: 'buy-it-29668.firebaseapp.com',
    storageBucket: 'buy-it-29668.appspot.com',
    measurementId: 'G-NFVL0LZEQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZGr3EfyM_8D5vAWXg2eZzuIMhC4R8qDc',
    appId: '1:278722220216:android:e745949180b26363eba44d',
    messagingSenderId: '278722220216',
    projectId: 'buy-it-29668',
    storageBucket: 'buy-it-29668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbvWrfVWl6jHPkt47XE_6p0uyNexIWLLc',
    appId: '1:278722220216:ios:5c1402919f2a494feba44d',
    messagingSenderId: '278722220216',
    projectId: 'buy-it-29668',
    storageBucket: 'buy-it-29668.appspot.com',
    iosBundleId: 'com.example.finalECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbvWrfVWl6jHPkt47XE_6p0uyNexIWLLc',
    appId: '1:278722220216:ios:5c1402919f2a494feba44d',
    messagingSenderId: '278722220216',
    projectId: 'buy-it-29668',
    storageBucket: 'buy-it-29668.appspot.com',
    iosBundleId: 'com.example.finalECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH_xARFXl7KFwcgB6__ox1BLOQZuWvlzY',
    appId: '1:278722220216:web:76344fdbe0a1d0bceba44d',
    messagingSenderId: '278722220216',
    projectId: 'buy-it-29668',
    authDomain: 'buy-it-29668.firebaseapp.com',
    storageBucket: 'buy-it-29668.appspot.com',
    measurementId: 'G-83HCHW9QKH',
  );
}
